from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint names are required for Alembic to autogenerate a correct
# `downgrade()` -- without this, Postgres assigns anonymous names to foreign keys/unique/check
# constraints and Alembic cannot emit a targeted DROP CONSTRAINT for them (confirmed: the
# `add_formulation_scoping_to_compound_aliases` migration's autogenerated downgrade failed with
# "Can't emit DROP CONSTRAINT for constraint ...; it has no name" before this convention was added).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models (backend/app/models/)."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
