"""initial schema

Revision ID: 656a21183cb0
Revises: 
Create Date: 2026-08-27 20:03:19.547342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656a21183cb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('parent_compound_id', sa.Integer(), nullable=True),
    sa.Column('pubchem_cid', sa.Integer(), nullable=True),
    sa.Column('chembl_id', sa.Text(), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('isomeric_smiles', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.Text(), nullable=True),
    sa.Column('molecular_formula', sa.Text(), nullable=True),
    sa.Column('molecular_weight', sa.Numeric(), nullable=True),
    sa.Column('drug_class', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_compound_id'], ['compounds.id'], name=op.f('fk_compounds_parent_compound_id_compounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compounds')),
    sa.UniqueConstraint('chembl_id', name=op.f('uq_compounds_chembl_id')),
    sa.UniqueConstraint('pubchem_cid', name=op.f('uq_compounds_pubchem_cid'))
    )
    op.create_index(op.f('ix_compounds_canonical_name'), 'compounds', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_compounds_inchikey'), 'compounds', ['inchikey'], unique=False)
    op.create_table('etl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='etlstatus'), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_runs'))
    )
    op.create_table('faers_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('source_report_id', sa.Text(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('age', sa.Numeric(), nullable=True),
    sa.Column('age_unit', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('serious', sa.Boolean(), nullable=True),
    sa.Column('seriousness_death', sa.Boolean(), nullable=True),
    sa.Column('seriousness_hospitalization', sa.Boolean(), nullable=True),
    sa.Column('is_deduplicated_latest', sa.Boolean(), nullable=False),
    sa.Column('dedup_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faers_reports')),
    sa.UniqueConstraint('case_id', 'version', name='uq_faers_case_version')
    )
    op.create_index(op.f('ix_faers_reports_case_id'), 'faers_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_faers_reports_received_date'), 'faers_reports', ['received_date'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('gene_symbol', sa.Text(), nullable=True),
    sa.Column('organism', sa.Text(), nullable=True),
    sa.Column('source_target_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    op.create_table('assays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_assay_id', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('assay_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organism', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('assay_format', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_assays_target_id_targets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assays')),
    sa.UniqueConstraint('source', 'source_assay_id', name='uq_assay_source_id')
    )
    op.create_table('faers_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('meddra_term', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['faers_reports.id'], name=op.f('fk_faers_reactions_report_id_faers_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faers_reactions'))
    )
    op.create_index(op.f('ix_faers_reactions_meddra_term'), 'faers_reactions', ['meddra_term'], unique=False)
    op.create_index(op.f('ix_faers_reactions_report_id'), 'faers_reactions', ['report_id'], unique=False)
    op.create_table('formulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('formulation_name', sa.Text(), nullable=False),
    sa.Column('ester_name', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], name=op.f('fk_formulations_compound_id_compounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formulations')),
    sa.UniqueConstraint('compound_id', 'formulation_name', name='uq_formulation_name')
    )
    op.create_index(op.f('ix_formulations_compound_id'), 'formulations', ['compound_id'], unique=False)
    op.create_table('report_classifications',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('use_classification', sa.Enum('THERAPEUTIC', 'MISUSE', 'MULTI_AAS_EXPOSURE', 'UNKNOWN', name='useclassification'), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('classifier_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['faers_reports.id'], name=op.f('fk_report_classifications_report_id_faers_reports')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_report_classifications'))
    )
    op.create_table('bioactivities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('assay_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.Enum('KI', 'IC50', 'EC50', 'KD', name='measurementtype'), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Numeric(), nullable=True),
    sa.Column('raw_units', sa.Text(), nullable=True),
    sa.Column('standardized_value_nm', sa.Numeric(), nullable=True),
    sa.Column('p_activity', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], name=op.f('fk_bioactivities_assay_id_assays')),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], name=op.f('fk_bioactivities_compound_id_compounds')),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_bioactivities_target_id_targets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bioactivities'))
    )
    op.create_index(op.f('ix_bioactivities_assay_id'), 'bioactivities', ['assay_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_compound_id'), 'bioactivities', ['compound_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_target_id'), 'bioactivities', ['target_id'], unique=False)
    op.create_table('compound_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('formulation_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.Enum('BRAND', 'COMMON_NAME', 'CHEMICAL_NAME', 'MISSPELLING', 'ABBREVIATION', 'OTHER', name='aliastype'), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], name=op.f('fk_compound_aliases_compound_id_compounds')),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], name=op.f('fk_compound_aliases_formulation_id_formulations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compound_aliases'))
    )
    op.create_index(op.f('ix_compound_aliases_compound_id'), 'compound_aliases', ['compound_id'], unique=False)
    op.create_table('faers_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_compound_id', sa.Integer(), nullable=True),
    sa.Column('formulation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('mapping_method', sa.Enum('EXACT_ALIAS', 'CURATED_MATCH', 'NORMALIZED_STRING_MATCH', 'FUZZY_HIGH_CONFIDENCE', 'MANUAL_REVIEW', 'UNMAPPED', name='mappingmethod'), nullable=False),
    sa.Column('mapping_confidence', sa.Numeric(), nullable=True),
    sa.Column('mapping_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], name=op.f('fk_faers_drugs_formulation_id_formulations')),
    sa.ForeignKeyConstraint(['normalized_compound_id'], ['compounds.id'], name=op.f('fk_faers_drugs_normalized_compound_id_compounds')),
    sa.ForeignKeyConstraint(['report_id'], ['faers_reports.id'], name=op.f('fk_faers_drugs_report_id_faers_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faers_drugs'))
    )
    op.create_index(op.f('ix_faers_drugs_normalized_compound_id'), 'faers_drugs', ['normalized_compound_id'], unique=False)
    op.create_index(op.f('ix_faers_drugs_report_id'), 'faers_drugs', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faers_drugs_report_id'), table_name='faers_drugs')
    op.drop_index(op.f('ix_faers_drugs_normalized_compound_id'), table_name='faers_drugs')
    op.drop_table('faers_drugs')
    op.drop_index(op.f('ix_compound_aliases_compound_id'), table_name='compound_aliases')
    op.drop_table('compound_aliases')
    op.drop_index(op.f('ix_bioactivities_target_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_compound_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_assay_id'), table_name='bioactivities')
    op.drop_table('bioactivities')
    op.drop_table('report_classifications')
    op.drop_index(op.f('ix_formulations_compound_id'), table_name='formulations')
    op.drop_table('formulations')
    op.drop_index(op.f('ix_faers_reactions_report_id'), table_name='faers_reactions')
    op.drop_index(op.f('ix_faers_reactions_meddra_term'), table_name='faers_reactions')
    op.drop_table('faers_reactions')
    op.drop_table('assays')
    op.drop_table('targets')
    op.drop_index(op.f('ix_faers_reports_received_date'), table_name='faers_reports')
    op.drop_index(op.f('ix_faers_reports_case_id'), table_name='faers_reports')
    op.drop_table('faers_reports')
    op.drop_table('etl_runs')
    op.drop_index(op.f('ix_compounds_inchikey'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_canonical_name'), table_name='compounds')
    op.drop_table('compounds')
    # ### end Alembic commands ###
    # NOTE (not autogenerated): op.drop_table() does not drop the native Postgres ENUM
    # types backing sa.Enum columns, so without these explicit drops a downgrade -> upgrade
    # round trip fails with "type already exists". See docs/database_schema.md.
    bind = op.get_bind()
    for enum_name in (
        'etlstatus', 'aliastype', 'useclassification', 'measurementtype', 'mappingmethod',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
